config/routes.rb
BookIt::Application.routes.draw do

  root 'resources#index'

  resources :resources do
    resources :bookings
  end

  

end

app/models/booking.rb
class Booking < ActiveRecord::Base

  belongs_to :resource

  validates :start_time, presence: true 
  validates :length, presence: true, numericality: { greater_than: 0 }
  validate :start_date_cannot_be_in_the_past
  validate :overlaps

  before_validation :calculate_end_time

  scope :end_during, ->(new_start_time, new_end_time) do
    if (!new_start_time.nil?) && (!new_end_time.nil?)
      where('end_time > ? AND end_time < ?', new_start_time, new_end_time)
    else
      return nil
    end
  end

  scope :start_during, ->(new_start_time, new_end_time) do
    if (!new_start_time.nil?) && (!new_end_time.nil?)
      where('start_time > ? AND start_time < ?', new_start_time, new_end_time)
    else
      return nil
    end
  end

  scope :happening_during, ->(new_start_time, new_end_time) do
    if (!new_start_time.nil?) && (!new_end_time.nil?)
      where('start_time > ? AND end_time < ?', new_start_time, new_end_time)
    else
      return nil
    end 
  end

  scope :enveloping, ->(new_start_time, new_end_time) do
    if (!new_start_time.nil?) && (!new_end_time.nil?)
      where('start_time < ? AND end_time > ?', new_start_time, new_end_time)
    else
      return nil
    end
  end

  scope :identical, ->(new_start_time, new_end_time) do
    if (!new_start_time.nil?) && (!new_end_time.nil?)
      where('start_time = ? AND end_time = ?', new_start_time, new_end_time)
    else
      return nil
    end
  end

  def overlaps
    overlapping_bookings = [ 
      resource.bookings.end_during(start_time, end_time),
      resource.bookings.start_during(start_time, end_time),
      resource.bookings.happening_during(start_time, end_time),
      resource.bookings.enveloping(start_time, end_time),
      resource.bookings.identical(start_time, end_time)
    ].flatten

    overlapping_bookings.delete self
    if overlapping_bookings.any?
      errors.add(:base, 'Slot has already been booked')
    end
  end

  def start_date_cannot_be_in_the_past
    if start_time && start_time < DateTime.now + (15.minutes)
      errors.add(:start_time, 'must be at least 15 minutes from present time')
    end
  end

  def calculate_end_time
    start_time = validate_start_time
    length = validate_length
    if start_time && length
      self.end_time = start_time + (length.hours - 60)
    end
  end

  def as_json(options = {})  
   {  
    :id => self.id,  
    :start => self.start_time,  
    :end => self.end_time + 60,
    :recurring => false, 
    :allDay => false
   }  
  end  

  private

    def validate_start_time
      if !self.start_time.nil?
        start_time = self.start_time
      else
        return nil
      end
    end

    def validate_length
      if !self.length.nil?
        length = self.length.to_i
      else
        return nil
      end
    end

end

app/models/resource.rb
class Resource < ActiveRecord::Base

  validates :name, 
    presence: true, 
    uniqueness: true

  has_many :bookings
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  respond_to :html, :xml, :json
  
  before_action :find_resource

  def index
    @bookings = Booking.where("resource_id = ? AND end_time >= ?", @resource.id, Time.now).order(:start_time)
    respond_with @bookings
  end

  def new
    @booking = Booking.new(resource_id: @resource.id)
  end

  def create
    @booking =  Booking.new(params[:booking].permit(:resource_id, :start_time, :length))
    @booking.resource = @resource
    if @booking.save
      redirect_to resource_bookings_path(@resource, method: :get)
    else
      render 'new'
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def destroy
    @booking = Booking.find(params[:id]).destroy
    if @booking.destroy
      flash[:notice] = "Booking: #{@booking.start_time.strftime('%e %b %Y %H:%M%p')} to #{@booking.end_time.strftime('%e %b %Y %H:%M%p')} deleted"
      redirect_to resource_bookings_path(@resource)
    else
      render 'index'
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    # @booking.resource = @resource

    if @booking.update(params[:booking].permit(:resource_id, :start_time, :length))
      flash[:notice] = 'Your booking was updated succesfully'

      if request.xhr?
        render json: {status: :success}.to_json
      else
        redirect_to resource_bookings_path(@resource)
      end
    else
      render 'edit'
    end
  end

  private

  def save booking
    if @booking.save
        flash[:notice] = 'booking added'
        redirect_to resource_booking_path(@resource, @booking)
      else
        render 'new'
      end
  end

  def find_resource
    if params[:resource_id]
      @resource = Resource.find_by_id(params[:resource_id])
    end
  end

end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController

  def index
    @resources = Resource.all
  end

  def new
    @resource = Resource.new
  end

  def create
    @resource = Resource.create(resource_params)
    if @resource.save
      name = @resource.name
      redirect_to resources_path
      flash[:notice] = "#{name} created"
    else
      render 'new'
      flash[:error] = "Unable to create resource. Please try again"
    end
  end

  def destroy
    @resource = Resource.find(params[:id])
    @resource.destroy
    redirect_to resources_path
  end

  def edit
    @resource = Resource.find(params[:id])
  end

  def update
    @resource = Resource.find(params[:id])
    @resource.update resource_params
    if @resource.save
      flash[:notice] = 'Your resource was updated succesfully'
      redirect_to root_path
    else
      render 'edit'
    end
  end

  private

    def resource_params
      params.require(:resource).permit(:name, :delete)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/views/bookings/_form.html.haml
/ = form_for @booking do |f|
/   - if @booking.errors.any?
/     .errors
/       %h3
/         = pluralize(@booking.errors.count, 'error')
/         prohibited this booking from being saved:
/       %ul
/         - @booking.errors.full_messages.each do |message|
/           %li= message
/   = f.label 'start_time', 'Start time'
/   = f.text_field 'start_time'
/   = f.label 'time_length', 'Length of time'
/   = f.number_field 'time_length'
/   = f.submit 'Submit'



= form_tag new_resource_booking_path do 

  - @resource.bookings.each do |booking| 

    = label_tag 'start_time', 'Start time'
    = text_field_tag 'start_time'
    = label_tag 'time_length', 'Length of time'
    = text_field_tag 'time_length'
    = submit_tag 'Submit'

app/views/bookings/edit.html.haml
%h3 
  Edit booking for 
  = @resource.name

- if @booking.errors.any?
  .errors
    %h3
      = pluralize(@booking.errors.count, 'error')
      prohibited this booking from being saved:
    %ul
      - @booking.errors.full_messages.each do |message|
        %li= message

= form_for([@resource, @booking]) do |f|
  %p
    = f.label 'start_time', 'Start time'
    = f.datetime_select :start_time, {minute_step: 15}
  %p
    = f.label 'length', 'Length of booking in hours'
    = f.number_field 'length'
  = f.submit 'Submit'

.calendar_container
  #calendar

app/views/bookings/index.html.haml
%h3 
  Bookings for
  = @resource.name
%table
  %tr
    %th
      Start
    %th
      End
  - @bookings.each do |booking|
    %tr
      %td
        = booking.start_time.strftime('%e %b %Y %H:%M%p')
      %td
        = (booking.calculate_end_time + 60).strftime('%e %b %Y %H:%M%p')
      %td= link_to "Delete", resource_booking_path(@resource, booking), data: { confirm: 'Are you sure?' }, method: :delete

      %td= link_to "Edit", edit_resource_booking_path(@resource, booking)

app/views/bookings/new.html.haml
%h3 
  Add booking for 
  = @resource.name

- if @booking.errors.any?
  .errors
    %h3
      = pluralize(@booking.errors.count, 'error')
      prohibited this booking from being saved:
    %ul
      - @booking.errors.full_messages.each do |message|
        %li= message

= form_for([@resource, @booking]) do |f|
  %p
    = f.label 'start_time', 'Start time'
    = f.datetime_select :start_time, {minute_step: 15}
  %p
    = f.label 'length', 'Length of booking in hours'
    = f.number_field 'length', min: 1
  = f.submit 'Submit'

.calendar_container
  #calendar

app/views/bookings/show.html.haml
%h3 
  Booking Confirmation
%p 
  Your booking is confirmed for
  = @resource.name
  ':'
  = @booking.start_time.strftime('%e %b %Y %H:%M%p')
  until
  = @booking.calculate_end_time

app/views/erb/bookings/_errors.html.erb
<%% if @booking.errors.any? %>
  <div class="errors">
    <h3><%%= pluralize(@booking.errors.count, 'error') %>
      prohibited this booking from being saved:
    </h3>
    <ul>
      <%% @booking.errors.full_messages.each do |message| %>
        <li><%%= message %></li>
      <%% end %>
    </ul>
  </div>
<%% end %>

app/views/erb/bookings/_form.html.erb
<%%= form_for([@resource, @booking]) do |f| %>
  <p>
    <%%= f.label 'start_time', 'Start time' %>
    <%%= f.datetime_select :start_time, { minute_step: 15 } %>
  </p>
  <p>
    <%%= f.label 'length', 'Length of booking in hours' %>
    <%%= f.number_field 'length', min: 1 %>
  </p>
  <%%= f.submit 'Submit' %>
<%% end %> 

app/views/erb/bookings/edit.html.erb
<h3>Edit booking for <%%= @resource.name %></h3>

<%%= render 'errors' %>
<%%= render 'form' %>

<div class="calendar_container">
  <div id="calendar">
  </div>
</div>

app/views/erb/bookings/index.html.erb
<h3> Bookings for <%%= @resource.name %></h3>
<table>
  <tr>
    <th>Start</th>
    <th>End</th>
  </tr>
  
  <%% @bookings.each do |booking| %>
  <tr>
    <td>
      <%%= booking.start_time.strftime('%e %b %Y %H:%M%p') %>
    </td>
    <td>
      <%%= booking.calculate_end_time.strftime('%e %b %Y %H:%M%p') %>
    </td>
    <td><%%= link_to "Delete", resource_booking_path(@resource, booking), data: { confirm: 'Are you sure?' }, method: :delete %>
    </td>
    <td><%%= link_to "Edit", edit_resource_booking_path(@resource, booking) %>
    </td>
  </tr>
  <%% end %>
</table>

app/views/erb/bookings/new.html.erb
<h3>Add booking for <%%= @resource.name %></h3>
  
<%%= render 'errors' %>
<%%= render 'form' %> 

<div class="calendar_container">
  <div id="calendar">
  </div>
</div>

app/views/erb/bookings/show.html.erb
<h3>Booking Confirmation</h3>
<p>Your booking is confirmed for
  <%%= @resource.name %>
  ':'
  <%%= @booking.start_time.strftime('%e %b %Y %H:%M%p') %>
  until
  <%%= (@booking.calculate_end_time + 60)strftime('%e %b %Y %H:%M%p') %>

app/views/erb/layouts/_flash.html.erb
<%%= flash[:notice] %>
<%%= flash[:alert] %>

app/views/erb/layouts/application.html.erb
<!DOCTYPE>
<html>
<head>     
<title> BookIt </title>
  <%%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%%= csrf_meta_tags %>
</head>
<body>
  <div class="wrapper">
      <%% if flash.notice || flash.alert %>
        <%%= render 'layouts/flash' %>
      <%% end %>
      <%%= yield %>
  </div>
</body>
<html/>

app/views/erb/resources/_errors.html.erb
<%% if @resource.errors.any? %>
  <div class="errors">
    <h3>
      <%%= pluralize(@resource.errors.count, 'error') %>
      prohibited this resource from being saved:
    </h3>
    <ul>
      <%% @resource.errors.full_messages.each do |message| %>
        <li><%%= message %></li>
      <%% end %>
    </ul>
  </div>
<%% end %>

app/views/erb/resources/_form.html.erb
<%%= form_for @resource do |f| %>
  <%%= render 'errors' %>
  <%%= f.label 'name', 'Name' %>
  <%%= f.text_field 'name', placeholder: 'Name'%>
  <%%= f.submit 'Submit' %>
<%% end %>

app/views/erb/resources/edit.html.erb
<%%= render 'form' %>

app/views/erb/resources/index.html.erb
<h3>Resources</h3>

<%% @resources.each do |resource| %>
  <div class="resource">
    <%%= resource.name %>
    <%%= link_to "Show all bookings", resource_bookings_path(resource) %>
    <%%= link_to "Delete", resource_path(resource), data: { confirm: 'Are you sure?' }, method: :delete %>
    <%%= link_to "Edit", edit_resource_path(resource) %>
    <%%= link_to "Add booking", new_resource_booking_path(resource) %>
  </div>
<%% end %>

app/views/erb/resources/new.html.erb
<%%= render 'form' %>

app/views/layouts/_flash.html.haml
= flash[:notice]
= flash[:alert]

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title BookIt
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .wrapper
      - if flash.notice || flash.alert
        = render 'layouts/flash'
      = yield

app/views/resources/_form.html.haml
= form_for @resource do |f|
  - if @resource.errors.any?
    .errors
      %h3
        = pluralize(@resource.errors.count, 'error')
        prohibited this resource from being saved:
      %ul
        - @resource.errors.full_messages.each do |message|
          %li= message
  = f.label 'name', 'Name'
  = f.text_field 'name', placeholder: 'Name'
  = f.submit 'Submit'

app/views/resources/edit.html.haml
= render 'form'

app/views/resources/index.html.haml
%h3 Resources
- @resources.each do |resource|
  .resource
    = resource.name
    = link_to "Show all bookings", resource_bookings_path(resource)
    = link_to "Delete", resource_path(resource), data: { confirm: 'Are you sure?' }, method: :delete
    = link_to "Edit", edit_resource_path(resource)
    = link_to "Add booking", new_resource_booking_path(resource)